server.port=8089
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey

#routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#service registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=60
eureka.instance.prefer-ip-address=true

#zipkin
#zipkin.web.rootUrl = http://localhost:9411/

#management.endpoints.web.exposure.include=*
spring.reactor.context-propagation=auto

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %c - %m%n


#logging
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.org.springframework.web=DEBUG


# UserService Login (Public)
spring.cloud.gateway.routes[0].id=UserServiceLogin
spring.cloud.gateway.routes[0].uri=lb://UserService
spring.cloud.gateway.routes[0].predicates[0]=Path=/ssms/userservice/auth/**

# Users (Protected)
spring.cloud.gateway.routes[1].id=UserServiceUsers
spring.cloud.gateway.routes[1].uri=lb://UserService
spring.cloud.gateway.routes[1].predicates[0]=Path=/ssms/userservice/users/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# Shippers (Protected)
spring.cloud.gateway.routes[2].id=UserServiceShippers
spring.cloud.gateway.routes[2].uri=lb://UserService
spring.cloud.gateway.routes[2].predicates[0]=Path=/ssms/userservice/shippers/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# ShipmentService Route (Protected)
spring.cloud.gateway.routes[3].id=ShipmentService
spring.cloud.gateway.routes[3].uri=lb://ShipmentService
spring.cloud.gateway.routes[3].predicates[0]=Path=/ssms/shipment/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter

# BillingService Route (Protected)
spring.cloud.gateway.routes[4].id=BillingService
spring.cloud.gateway.routes[4].uri=lb://BillingService
spring.cloud.gateway.routes[4].predicates[0]=Path=/ssms/billing/**
spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter

#For Angular, Cors
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=false
